#Python Basics

In [1]:
print('welcome to the revision class of python')

welcome to the revision class of python


In [2]:
if 6>2:
  print('welcome to the revision class of python')

welcome to the revision class of python


In [3]:
if 5>12:
  print('welcome to the revision class of python')
else:
  print('ok')

ok


In [4]:
x=5
y='hello world'

In [5]:
x

5

In [6]:
y

'hello world'

In [7]:
x=7
y='hello world'
print(x)
print(y)

7
hello world


In [8]:
x=b"hello"
print(type(x))
print(x)

<class 'bytes'>
b'hello'


In [9]:
x=bytearray(4)
print(x)

bytearray(b'\x00\x00\x00\x00')


In [10]:
#python numbers
x=1   #int
y=6.9 #float
z=6j  #complex

In [11]:
x

1

In [12]:
y

6.9

In [13]:
z

6j

In [14]:
print(x)
print(type(x))

1
<class 'int'>


In [15]:
print(y)
print(type(y))

6.9
<class 'float'>


In [16]:
print(z)
print(type(z))

6j
<class 'complex'>


In [17]:
x=int(8)
y=int(9.8)
z=int("3")
print(x)
print(y)
print(z)

8
9
3


In [18]:
x=str(8)
y=str(9.8)
z=str("3")
print(x)
print(y)
print(z)
print(type(x))
print(type(y))
print(type(z))

8
9.8
3
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
a=""" aditya has a doubt,
which is regarding scan,
we need to adress,
the topic."""
print(a)

 aditya has a doubt,
which is regarding scan,
we need to adress,
the topic.


In [20]:
print(10>9)
print(10==9)
print(10<9)

True
False
False


#Lists

In [21]:
thisislist=['apple','banana','grapes']
thisislist

['apple', 'banana', 'grapes']

In [22]:
type(thisislist)

list

In [23]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
print(thisislist)

['apple', 'banana', 'grapes', 'apple1', 'banana1', 'grapes1']


In [24]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
print(thisislist[1])

banana


In [25]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
print(thisislist[0:4])

['apple', 'banana', 'grapes', 'apple1']


In [26]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
print(thisislist[:4])

['apple', 'banana', 'grapes', 'apple1']


In [27]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
print(thisislist[2:])

['grapes', 'apple1', 'banana1', 'grapes1']


In [28]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
thisislist[1]='bingo'
print(thisislist)

['apple', 'bingo', 'grapes', 'apple1', 'banana1', 'grapes1']


In [29]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
thisislist[1]=['bingo','mango']
print(thisislist)

['apple', ['bingo', 'mango'], 'grapes', 'apple1', 'banana1', 'grapes1']


In [30]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
thisislist.append('orange')
print(thisislist)

['apple', 'banana', 'grapes', 'apple1', 'banana1', 'grapes1', 'orange']


In [31]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
thisislist.insert(2,'orange')
print(thisislist)

['apple', 'banana', 'orange', 'grapes', 'apple1', 'banana1', 'grapes1']


In [32]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
tropical=['mango','pineapple','papaya','mango1','pineapple1','papaya1']
thisislist.extend(tropical)
print(thisislist)

['apple', 'banana', 'grapes', 'apple1', 'banana1', 'grapes1', 'mango', 'pineapple', 'papaya', 'mango1', 'pineapple1', 'papaya1']


In [33]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
thisistuple=('mango','pineapple','papaya','mango1','pineapple1','papaya1')
thisislist.extend(thisistuple)
print(thisislist)

['apple', 'banana', 'grapes', 'apple1', 'banana1', 'grapes1', 'mango', 'pineapple', 'papaya', 'mango1', 'pineapple1', 'papaya1']


In [34]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
tropical=['mango','pineapple','papaya','mango1','pineapple1','papaya1']
thisislist.remove('apple1')
print(thisislist)

['apple', 'banana', 'grapes', 'banana1', 'grapes1']


In [35]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
tropical=['mango','pineapple','papaya','mango1','pineapple1','papaya1']
thisislist.pop(0)
print(thisislist)

['banana', 'grapes', 'apple1', 'banana1', 'grapes1']


In [36]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
tropical=['mango','pineapple','papaya','mango1','pineapple1','papaya1']
del thisislist #thisislist gets deleted

In [37]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
tropical=['mango','pineapple','papaya','mango1','pineapple1','papaya1']
thisislist.clear()
print(thisislist)

[]


##loops through list

In [38]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
for x in thisislist:
  print(x)

apple
banana
grapes
apple1
banana1
grapes1


In [39]:
thisislist=['apple','banana','grapes','apple1','banana1','grapes1']
i=0
while i<len(thisislist):
 print(thisislist[i])
 i+=1

apple
banana
grapes
apple1
banana1
grapes1


In [40]:
thislist=['apple','banana','cherry']
[print (x) for x in thislist]

apple
banana
cherry


[None, None, None]

In [41]:
fruits=['apple','banana','cherry','kiwi','mango']
newlist=[]
for x in fruits:
    if 'a' in x:
     newlist.append(x)
print(newlist)


['apple', 'banana', 'mango']


In [42]:
fruits=['apple','banana','cherry','kiwi','mango']
newlist=[x for x in fruits if 'a' in x]
print(newlist)

['apple', 'banana', 'mango']


In [43]:
fruits=['apple','banana','cherry','kiwi','mango']
fruits.sort()
print(fruits)

['apple', 'banana', 'cherry', 'kiwi', 'mango']


In [44]:
thislist=["orange","mango","kiwi","pineapple","banana"]
thislist.sort()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']


In [45]:
thislist=[100,40,50,2,22,83,78]
thislist.sort()
print(thislist)

[2, 22, 40, 50, 78, 83, 100]


In [46]:
thislist=["orange","mango","kiwi","pineapple","banana"]
thislist.sort(reverse=True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']


In [47]:
thislist=[100,40,50,2,22,83,78]
thislist.sort(reverse=True)
print(thislist)

[100, 83, 78, 50, 40, 22, 2]


In [48]:
thislist=["orange","mango","kiwi","pineapple","banana"]
newlist=thislist.copy()
print(newlist)

['orange', 'mango', 'kiwi', 'pineapple', 'banana']


In [49]:
thislist=[100,40,50,2,22,83,78]
newlist=thislist.copy()
print(newlist)

[100, 40, 50, 2, 22, 83, 78]


In [50]:
thislist1=["orange","mango","kiwi","pineapple","banana"]
thislist2=[100,40,50,2,22,83,78]
list3=thislist1+thislist2
print(list3)

['orange', 'mango', 'kiwi', 'pineapple', 'banana', 100, 40, 50, 2, 22, 83, 78]


In [51]:
thislist1=["orange","mango","kiwi","pineapple","banana"]
thislist2=[100,40,50,2,22,83,78]
for x in thislist2:
 thislist1.append(x)
print(thislist1)

['orange', 'mango', 'kiwi', 'pineapple', 'banana', 100, 40, 50, 2, 22, 83, 78]


In [52]:
thislist1=["orange","mango","kiwi","pineapple","banana"]
thislist2=[100,40,50,2,22,83,78]
thislist1.extend(thislist2)
print(thislist1)

['orange', 'mango', 'kiwi', 'pineapple', 'banana', 100, 40, 50, 2, 22, 83, 78]


In [53]:
l=['k','a','r','u','n']
p=['n','a','y','a','r']
l.extend(p)
print(l)

['k', 'a', 'r', 'u', 'n', 'n', 'a', 'y', 'a', 'r']


In [54]:
l=['k','a','r','u','n']
p=['n','a','y','a','r']
o=l+p
print(o)

['k', 'a', 'r', 'u', 'n', 'n', 'a', 'y', 'a', 'r']


In [55]:
l=['k','a','r','u','n']
print(l)

['k', 'a', 'r', 'u', 'n']


#Tuple:
are used to store multiple items in a single variable


list-tuple:tuple is unchangable unlike list, tuple is created by using parantheses

In [56]:
thisistuple=('cherry','banana','apple')
print(thisistuple)

('cherry', 'banana', 'apple')


In [57]:
thisistuple=('cherry','banana','apple','cherry','banana','apple')
print(thisistuple)

('cherry', 'banana', 'apple', 'cherry', 'banana', 'apple')


In [58]:
thisistuple=('cherry','banana','apple','cherry','banana','apple')
print(len(thisistuple))

6


In [59]:
tuple1=("orange","mango","kiwi","pineapple","banana")
tuple2=(100,40,50,2,22,83,78)
tuple3=(True,False,False)
print(tuple1)
print(tuple2)
print(tuple3)

('orange', 'mango', 'kiwi', 'pineapple', 'banana')
(100, 40, 50, 2, 22, 83, 78)
(True, False, False)


In [60]:
tuple1=("orange",3,True,"pineapple","banana")
tuple2=(100,40,50,2,22,83,78)
tuple3=(True,False,False)
print(tuple1)
print(type(tuple1))


('orange', 3, True, 'pineapple', 'banana')
<class 'tuple'>


In [61]:
tuple1=("orange",3,True,"pineapple","banana")
print(tuple1[1])

3


In [62]:
tuple1=("orange",3,True,"pineapple","banana")
print(tuple1[-2])

pineapple


In [63]:
tuple1=("orange",3,True,"pineapple","banana")
print(tuple1[:4])

('orange', 3, True, 'pineapple')


In [64]:
tuple1=("orange",3,True,"pineapple","banana")
print(tuple1[1:7])

(3, True, 'pineapple', 'banana')


In [65]:
x=('apple','banana','cherry')
y=list(x)
y[1]='kiwi'
x=tuple(y)
print(x)

('apple', 'kiwi', 'cherry')


In [66]:
tuple1=("orange",3,True,"pineapple","banana")
y=list(tuple1)
y.append('apple')
tuple1=tuple(y)
print(tuple1)

('orange', 3, True, 'pineapple', 'banana', 'apple')


In [67]:
tuple1=("orange",3,True,"pineapple","banana")
y=list(tuple1)
y.remove('banana')
tuple1=tuple(y)
print(tuple1)

('orange', 3, True, 'pineapple')


In [68]:
colours=("orange","pineapple","banana")
(green,yellow,red)=colours
print(green)
print(yellow)
print(red)

orange
pineapple
banana


In [69]:
colours=("orange","pineapple","banana","cherry","mango")
(green,yellow,*red)=colours
print(green)
print(yellow)
print(red)

orange
pineapple
['banana', 'cherry', 'mango']


In [70]:
colours=("orange","pineapple","banana","cherry","mango")
(green,*yellow,red)=colours
print(green)
print(yellow)
print(red)

orange
['pineapple', 'banana', 'cherry']
mango


In [71]:
colours=("orange","pineapple","banana","cherry","mango")
for x in colours:
  print(x)

orange
pineapple
banana
cherry
mango


In [72]:
colours=("orange","pineapple","banana","cherry","mango")
for i in range(len(colours)):
  print(colours[i])

orange
pineapple
banana
cherry
mango


#Dictionaries

In [73]:
thisdict={"brand":"ford","model":"mustang","year":1964}
print(thisdict)

{'brand': 'ford', 'model': 'mustang', 'year': 1964}


In [74]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":1964,"colour":["red","white","blue"]}
print(thisdict)

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'year': 1964, 'colour': ['red', 'white', 'blue']}


In [75]:
print(type(thisdict))

<class 'dict'>


In [76]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":1964,"colour":["red","white","blue"]}
thisdict["year"]= 2020
print(thisdict)
print(len(thisdict["colour"]))

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'year': 2020, 'colour': ['red', 'white', 'blue']}
3


In [77]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":2022,"colour":["red","white","blue"]}
thisdict.update({"aditya":"first owner"})
print(thisdict)

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'year': 2022, 'colour': ['red', 'white', 'blue'], 'aditya': 'first owner'}


In [78]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":2022,"colour":["red","white","blue"]}
thisdict.pop("colour")
print(thisdict)

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'year': 2022}


In [79]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":2022,"colour":["red","white","blue"]}
del thisdict["year"]
print(thisdict)

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'colour': ['red', 'white', 'blue']}


In [80]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":2022,"colour":["red","white","blue"]}
thisdict.clear()
print(thisdict)

{}


In [81]:
thisdict={"brand":"ford","model":"mustang","country":"india","year":2022,"colour":["red","white","blue"]}
newdict=thisdict.copy()
print(newdict)

{'brand': 'ford', 'model': 'mustang', 'country': 'india', 'year': 2022, 'colour': ['red', 'white', 'blue']}


In [82]:
thisdict={"child1":{"name":"mansi","year":2002},"child2":{"name":"vikas","year":1985},"child3":{"name":"payal","year":2007}}
print(thisdict)

{'child1': {'name': 'mansi', 'year': 2002}, 'child2': {'name': 'vikas', 'year': 1985}, 'child3': {'name': 'payal', 'year': 2007}}


##Dictionary methods

**1)clear() , 2)copy() , 3)fromkey() , 4)get() , 5)items() , 6)keys() , 7)pop() , 8)popitem() , 9)setdefault() , 10)update() , 11)values()**

In [83]:
a=33
b=200
if b>a :
  print("b is greater")


b is greater


In [84]:
a=33
b=33
if b>a :
  print("b is greater")
elif a==b :
  print("a and b are equal")


a and b are equal


In [85]:
a=333
b=33
if b>a :
  print("b is greater")
elif a==b :
  print("a and b are equal")
else :
  print("a is greater than b")

a is greater than b


In [86]:
a=332

b=33
if b>a :
  print("b is greater")
else :
  print("a is greater than b")

a is greater than b


In [87]:
a=333
b=3333
if b>a : print("b is greater")

b is greater


In [88]:
a=333
b=33
c=444
if a>b and c>a :
  print("both conditions are true.",a,"and",c,"are greater than",b)

both conditions are true. 333 and 444 are greater than 33


In [89]:
a=333
b=33
c=444
if b>a or c>a :
  print("at least one of the conditions is true")

at least one of the conditions is true


#Pandas

##Concatenetion

In [90]:
import pandas as pd
df1=pd.DataFrame({'item':['a','b','c','d'],'value':[1,2,3,5]})
df2=pd.DataFrame({'item':['e','f','g','h'],'value':[5,6,7,8]})
print(df1)
print(df2)

  item  value
0    a      1
1    b      2
2    c      3
3    d      5
  item  value
0    e      5
1    f      6
2    g      7
3    h      8


In [91]:
df1

item  value
0    a      1
1    b      2
2    c      3
3    d      5

In [92]:
df2

item  value
0    e      5
1    f      6
2    g      7
3    h      8

In [93]:
pd.concat([df1,df2])

item  value
0    a      1
1    b      2
2    c      3
3    d      5
0    e      5
1    f      6
2    g      7
3    h      8

In [94]:
import pandas as pd
df1=pd.DataFrame({'item':['a','b','c','d'],'value':[1,2,3,5]})
df2=pd.DataFrame({'item':['e','f','g','h'],'value':[6,7,8,9]})
print(df1)
print(df2)

  item  value
0    a      1
1    b      2
2    c      3
3    d      5
  item  value
0    e      6
1    f      7
2    g      8
3    h      9


In [95]:
pd.concat([df1,df2])

item  value
0    a      1
1    b      2
2    c      3
3    d      5
0    e      6
1    f      7
2    g      8
3    h      9

In [96]:
df1=pd.DataFrame({'item':['a','b','c','d'],'value':[1,2,3,5]})
df2=pd.DataFrame({'item':['e','f','g','h'],'quantity':[5,6,7,8]})
pd.concat([df1,df2])

item  value  quantity
0    a    1.0       NaN
1    b    2.0       NaN
2    c    3.0       NaN
3    d    5.0       NaN
0    e    NaN       5.0
1    f    NaN       6.0
2    g    NaN       7.0
3    h    NaN       8.0

In [97]:
df1=pd.DataFrame({'item':['a','b','c','d'],'value':[1,2,3,5]})
df2=pd.DataFrame({'item':['e','f','g','h'],'quantity':[5,6,7,8]})
pd.concat([df1,df2]).reset_index()

index item  value  quantity
0      0    a    1.0       NaN
1      1    b    2.0       NaN
2      2    c    3.0       NaN
3      3    d    5.0       NaN
4      0    e    NaN       5.0
5      1    f    NaN       6.0
6      2    g    NaN       7.0
7      3    h    NaN       8.0

In [98]:
pd.concat([df1,df2], axis=1)

item  value item  quantity
0    a      1    e         5
1    b      2    f         6
2    c      3    g         7
3    d      5    h         8

##Append & Merge

In [99]:
df1=pd.DataFrame({'item':['a','b','c','d'],'value':[1,2,3,5]})
df2=pd.DataFrame({'item':['e','f','g','h'],'quantity':[5,6,7,8]})
df3=pd.DataFrame({'item':['i','j','k','l'],'quantity':[3,7,4,25]})
df1.append([df2,df3])

item  value  quantity
0    a    1.0       NaN
1    b    2.0       NaN
2    c    3.0       NaN
3    d    5.0       NaN
0    e    NaN       5.0
1    f    NaN       6.0
2    g    NaN       7.0
3    h    NaN       8.0
0    i    NaN       3.0
1    j    NaN       7.0
2    k    NaN       4.0
3    l    NaN      25.0

In [100]:
dfa=pd.DataFrame({'key':['a','b','c','d'],'A':[1,2,3,5]})
dfb=pd.DataFrame({'key':['e','f','g','h'],'B':[5,6,7,8]})
pd.merge(dfa,dfb, on='key')


Empty DataFrame
Columns: [key, A, B]
Index: []

In [101]:
dfa=pd.DataFrame({'key':['k0','k1','k2','k3'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
dfb=pd.DataFrame({'key':['k0','k1','k2','k3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})
pd.merge(dfa,dfb, on='key')


key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [102]:
dfa=pd.DataFrame({'key':['k0','k1','k2','k3'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
dfb=pd.DataFrame({'key':['k0','k1','k2','k3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})
pd.merge(dfa,dfb,how='left', on='key')


key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [103]:
dfa=pd.DataFrame({'key':['k0','k1','k2','k3'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
dfb=pd.DataFrame({'key':['k0','k1','k2','k3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})
pd.merge(dfa,dfb,how='right', on='key')


key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [104]:
dfa=pd.DataFrame({'key':['k0','k1','k2','k3'],'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']})
dfb=pd.DataFrame({'key':['k0','k1','k2','k3'],'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']})
pd.merge(dfa,dfb,how='inner', on='key')


key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [105]:
left=pd.DataFrame({'A':['k0','k1','k2','k3'],'b':['A0','A1','A2','A3']},index=['B0','B1','B2','B3'])


In [106]:
left

A   b
B0  k0  A0
B1  k1  A1
B2  k2  A2
B3  k3  A3

In [107]:
left=pd.DataFrame({'A':['A0','A1','A2'],'b':['B0','B1','B2']},index=['K0','K1','K2'])
left

A   b
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [108]:
right=pd.DataFrame({'c':['c0','c1','c2'],'d':['d0','d1','d2']},index=['K0','K1','K2'])
right

c   d
K0  c0  d0
K1  c1  d1
K2  c2  d2

In [109]:
left.join(right)

A   b   c   d
K0  A0  B0  c0  d0
K1  A1  B1  c1  d1
K2  A2  B2  c2  d2

In [110]:
left.join(right,how='outer')

A   b   c   d
K0  A0  B0  c0  d0
K1  A1  B1  c1  d1
K2  A2  B2  c2  d2

#Loops

***nested if***

In [111]:
x=42
if x>10:
  print("value is greater than 10")
  if x>20:
    print("value is greater than 20")
else:
  print("value is less than 10")

value is greater than 10
value is greater than 20


***while loop***

In [112]:
i=1
while i<6 :
  print(i)
  i+=1


1
2
3
4
5


In [113]:
i=1
while i<6 :
  print(i)
  if i==3:
    break
  i+=1


1
2
3


In [114]:
i=1
while i<6 :
  print(i)
  i+=1
else:
  print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


#Numpy

In [115]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)
print(type(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


In [116]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(arr)
print(type(arr))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
<class 'numpy.ndarray'>


In [117]:
import numpy as np
a=np.array(456)
b=np.array([1,2,3,4,5,6,7])
c= np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [118]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[2]+arr[4])

8


In [119]:
import numpy as np
c=np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)
print('3rd element on 2nd array of 1st array:',c[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
3rd element on 2nd array of 1st array: 6


In [120]:
import numpy as np
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element of 2nd dim:', c[1,-1])

last element of 2nd dim: 10


In [121]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:6])
print(c[1:5])

[2 3 4 5 6]
[2 3 4 5]


In [122]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[5:])

[ 6  7  8  9 10]


In [123]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[:8])

[1 2 3 4 5 6 7 8]


In [124]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:-2])

[2 3 4 5 6 7 8]


In [125]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[-3:-1])

[8 9]


In [126]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:3])

[2 5]


In [127]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[1:5:2])

[2 4]


In [128]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c[::2])

[1 3 5 7 9]


In [129]:
import numpy as np
c=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(c[0:4,0:3])

[[1 2 3]
 [6 7 8]]


In [130]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10])
print(c.dtype)

int64


In [131]:
import numpy as np
c=np.array(['madhu','sai','mansi','payal','ashwini','rahul'])
print(c.dtype)

<U7


In [132]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
newarray=c.astype(int)
print(newarray)
print(newarray.dtype)

[1 2 3 4]
int64


In [133]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
newarray=c.astype(bool)
print(newarray)
print(newarray.dtype)

[ True  True  True  True]
bool


In [134]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
x=c.copy()
print(x)
print(x.dtype)

[1.23 2.34 3.44 4.44]
float64


In [135]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
x=c.view()
x[0]=34
print(x)
print(x.dtype)

[34.    2.34  3.44  4.44]
float64


In [136]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
x=c.view()#print the value of base attribute at the end to check if ana rray owns its data or not
y=c.copy()
print(x)
print(y)
print(x.base)
print(y.base)
print(x.dtype)

[1.23 2.34 3.44 4.44]
[1.23 2.34 3.44 4.44]
[1.23 2.34 3.44 4.44]
None
float64


In [137]:
import numpy as np
c=np.array([1.23,2.34,3.44,4.44])
y=np.array([[1,2,3,4,5],[6,7,8,9,10,]])
print(c.shape)
print(y.shape)

(4,)
(2, 5)


In [138]:
import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarray=c.reshape(4,3)
print(c)
print(newarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [139]:

import numpy as np
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarray=c.reshape(2,3,2)
print(c)
print(newarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [140]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
newarray=arr.reshape(-1)
print(newarray)

[1 2 3 4 5 6]


In [141]:

import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.concatenate((arr1,arr2))
print(arr1)
print(arr2)
print(newarray)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [142]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.stack((arr1,arr2),axis=0)
print(arr1)
print(arr2)
print(newarray)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [143]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.stack((arr1,arr2),axis=1)
print(arr1)
print(arr2)
print(newarray)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [144]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.hstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarray)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [145]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.vstack((arr1,arr2))
print(arr1)
print(arr2)
print(newarray)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [146]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarray=np.dstack((arr1,arr2))
print(newarray)

[[[1 4]
  [2 5]
  [3 6]]]


##Split the array##

In [147]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarray=np.array_split(arr1,3)
print(arr1)
print(newarray)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [148]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
newarray=np.array_split(arr1,4)
print(arr1)
print(newarray)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [149]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarray=np.array_split(arr,3)
print(newarray[0])
print(newarray[1])
print(newarray[2])

[1 2]
[3 4]
[5 6]


In [150]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
newarray=np.where(arr==3)
print(newarray)

(array([2]),)


In [151]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
newarray=np.where(arr==4)
print(newarray)

(array([3, 5, 6]),)


In [152]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarray=np.where(arr%2==0)
print(newarray)

(array([1, 3, 5, 7]),)


In [153]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarray=np.where(arr%2==1)
print(newarray)

(array([0, 2, 4, 6]),)


In [154]:
import numpy as np
arr=np.array([6,7,8,9])
newarray=np.searchsorted(arr,7)
print(newarray)

1


In [155]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarray=np.where(arr==7)
print(newarray)

(array([6]),)


In [156]:
import numpy as np
arr=np.array([6,7,8,9])
newarray=np.searchsorted(arr,7,side='right')
print(newarray)

2


In [157]:
import numpy as np
arr=np.array([41,42,43,44])
x=arr[[True,False,True,False]]
print(x)

[41 43]


In [158]:
import numpy as np
arr=np.array([1,2,3,5])
x=arr[[True,True,True,False]]
print(x)

[1 2 3]


In [159]:
import numpy as np
arr=np.array([1,2,3,5])
filter_arr=arr>2
newarray=arr[filter_arr]
print(filter_arr)
print(newarray)

[False False  True  True]
[3 5]


# ***Python program to find the L.C.M of 2 input numbers***

In [160]:
def lcm(x,y):
  if x>y:
    greater = x
  else:
    greater=y
  while(True):
    if ((greater%x==0) and (greater%y==0)):
      lcm=greater
      break
    greater+=1
  return lcm
num1=int(input("enter first number:"))
num2=int(input("enter second number:"))
print("lcm of",num1,"and",num2,"is",lcm(num1,num2))

enter first number:4
enter second number:8
lcm of 4 and 8 is 8


#Python program for finding H.C.F of two input numbers

In [161]:
#python program for finding H.C.F of two input numbers
def computeHCF(x,y):


#choose the smaller number
  if x>y:
    smaller=y
  else:
    smaller=x
  for i in range(1,smaller+1):
    if ((x%i)==0) and ((y%i)==0):
      hcf=i
  return hcf
num1=int(input("enter first number"))
num2=int(input("enter second number"))
print("HCF of",num1,"and",num2,"is",computeHCF(num1,num2))

enter first number10
enter second number20
HCF of 10 and 20 is 10


In [162]:
computeHCF(5,10)

5